version: '3'

services:
  minio:
    build: .
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminuser
    networks:
      - frontend
      - backend


networks:
  frontend:
  backend:

volumes:
  minio: